version: "3.3"

services:
  php:
    image: registry.zscorp.com.tw/zscorp/laravel-shared-php:8.1-fpm
    restart: always
    working_dir: "/app/backend"
    volumes:
      - "./backend:/app/backend"
      - "./config/cron.d/cron-laravel:/etc/cron.d/cron-laravel"
      - "./log/php:/var/log"
    depends_on:
      - mysql
    # extra_hosts: # 連接共用容器的 MySQL 資料庫，docker 給的虛擬 ip 是 172.17.0.1
    #   - "mysql:172.17.0.1"
 
  node:
    image: node:20
    restart: always
    # build: .# Dockerfile 安裝 gitlab-runner 太久超過 2 小時，使用  --no-install-recommends 安裝也一樣，所以先不在此 service 安裝 gitlab-runner
    working_dir: /usr/src/app
    volumes:
      #- ./config/gitlab-runner:/etc/gitlab-runner
      - ./frontend:/usr/src/app
      - ./build:/usr/src/dist
    environment:
      - NODE_ENV=development
    #command: sh -c "npm install && npm run build" # 第一次執行環境，執行此指令 build 前端程式
    #command: sh -c "gitlab-runner start && /bin/bash" # 後續執行環境，因為都是用 gitlab-runner 更新所已預設此指令
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    
  mysql:
    image: mysql:5
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
    ports:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./log/nginx:/var/log/nginx" # Nginx 的 access log 以及 error log
      - "./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf" # Nginx 設定檔
      - "./certbot/conf:/etc/letsencrypt:ro" # Save Certifaction
      - "./certbot/www:/var/www/certbot:ro" # Save Let's encrypt acme challenge
      - "./backend:/app/backend" # Laravel 後端的整包檔案
      - "./build:/app/frontend"
    depends_on:
      - php
    entrypoint: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; filename=\"/etc/letsencrypt/live/xindian.waytogolf.com.tw/fullchain.pem\";m1=$$(md5sum \"$$filename\");while true;do sleep 12h; m2=$$(md5sum \"$$filename\"); if [ \"$$m1\" != \"$$m2\" ] ;then echo \"NOTICE: Letsencrypt fullchain.pem has changed!\" >&2; nginx -s reload; break; fi done; done & nginx -g \"daemon off;\"'" #因為 certbot 憑證若過期會自動更新，所以 nginx 須設定此指令才不會無法讀新的憑證

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - "./certbot/conf:/etc/letsencrypt:rw" # Save Certifaction
      - "./certbot/db:/var/lib/letsencrypt"
      - "./certbot/logs:/var/log/letsencrypt"
      - "./certbot/www:/var/www/certbot:rw"
    entrypoint: "/bin/sh -c 'mkdir -p /tmp; chmod 1777 /tmp; trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
